OBJECTS = filecach${OBJ_SUFF} bitset${OBJ_SUFF} \
          signal${OBJ_SUFF} archcach${OBJ_SUFF} \
          cacharch${OBJ_SUFF} cachamem${OBJ_SUFF} \
			 cond${OBJ_SUFF} condeval${OBJ_SUFF}
                     
.ifdef WIN32
ODEDLLPORT=
.endif

# When library files are compiled, assume a DLL will be created
BUILD_SHARED_OBJECTS =

.include <${RULES_MK}>

