PROGRAMS = tdirent${PROG_SUFF} tproc${PROG_SUFF} tdir${PROG_SUFF} \
           tfile${PROG_SUFF} tarch${PROG_SUFF} tPOSIXregex${PROG_SUFF} \
           tregex${PROG_SUFF}

LIBS     = ${LIB_PREF}${ODELIBNAME}${LIB_SUFF}

.include <${RULES_MK}>
