OBJECTS = \
	  genpath${OBJ_SUFF} \
	  mkdep${OBJ_SUFF} depmkfil${OBJ_SUFF} body${OBJ_SUFF} \
	  misc${OBJ_SUFF}

# When DLL files are compiled, they should NOT use the Import keyword
ODEDLLPORT =

# When library files are compiled, assume a DLL will be created
BUILD_SHARED_OBJECTS =

.include <${RULES_MK}>
