PROGRAMS = tst${PROG_SUFF} tstfc${PROG_SUFF} tbitset${PROG_SUFF} \
           tarch${PROG_SUFF} ttool${PROG_SUFF} tcond${PROG_SUFF} \
           tcndeval${PROG_SUFF}

LIBS = ${LIB_PREF}${ODELIBNAME}${LIB_SUFF}

.include <${RULES_MK}>
