JAVA_CLASSES = B390LSTFormatter${CLASS_SUFF} \
               B390NodeHandler${CLASS_SUFF} \
               B390UPDFormatter${CLASS_SUFF} \
               Cmvc2B390${CLASS_SUFF} \
               Formatter${CLASS_SUFF} \
               LSTFormatter${CLASS_SUFF} \
               MkinstallNodeHandler${CLASS_SUFF} \
               MkinstallTreeCustomizer${CLASS_SUFF} \
               MVSTreeCustomizer${CLASS_SUFF} \
               NodeHandler${CLASS_SUFF} \
               TreeCustomizer${CLASS_SUFF} \
               TreeHandler${CLASS_SUFF} 

.include <${RULES_MK}>















