JAVA_CLASSES = FixStrategy${CLASS_SUFF} \
               PackageClassification${CLASS_SUFF} \
               PackageConstants${CLASS_SUFF} \
               CommonInterfaceStrings${CLASS_SUFF}  \
               SystemVariableNotFoundError${CLASS_SUFF} \
               PackageType${CLASS_SUFF} \
               PkgApiUtil${CLASS_SUFF}

.include <${RULES_MK}>

