PROGRAMS = tblstcf${PROG_SUFF} tui${PROG_SUFF} tsetscf${PROG_SUFF} \
           tsvarcf${PROG_SUFF} tsbrdr${PROG_SUFF} tsbrccf${PROG_SUFF} \
           tsandbox${PROG_SUFF} tfile${PROG_SUFF} tpath${PROG_SUFF} \
           testfic${PROG_SUFF}

LIBS     = ${LIB_PREF}${ODELIBNAME}${LIB_SUFF}

.include <${RULES_MK}>
