# Class files to generate
JAVA_CLASSES = Version${CLASS_SUFF} UsagePrintable${CLASS_SUFF} \
               StringTools${CLASS_SUFF} Interface${CLASS_SUFF} \
               Path${CLASS_SUFF} CommandLine${CLASS_SUFF}

# Name of the package that the Java files in this directory are a part of
JAVA_PACKAGE_NAME = COM.ibm.makemake.lib

.include <${RULES_MK}>
