OBJECTS = ui${OBJ_SUFF} cmdline${OBJ_SUFF} path${OBJ_SUFF} filec${OBJ_SUFF} \
	  version${OBJ_SUFF} cfgf${OBJ_SUFF} setvarcf${OBJ_SUFF} \
	  bldlstcf${OBJ_SUFF} sbrccf${OBJ_SUFF} \
	  sbcnfrdr${OBJ_SUFF} sandbox${OBJ_SUFF}

# When DLL files are compiled, they should NOT use the Import keyword
ODEDLLPORT =

# When library files are compiled, assume a DLL will be created
BUILD_SHARED_OBJECTS =

.include <${RULES_MK}>
