ILIST = \
  Config.pm \
  Fileset.pm \
  Log.pm \
  Object.pm \
  Packager.pm \
  Parser.pm \
  Tokenizer.pm \
  Product.pm \
  Update.pm

IDIR = ${IDIR_PREF}/opt/pkgtools/rte/lib/Pkg/

.include <${RULES_MK}>
