SUBDIRS = service
OBJECTS_SUBDIRS = service
JAVA_CLASSES = ArchitectureInfoAttribObject${CLASS_SUFF} \
               AttributeCollection${CLASS_SUFF} \
               AttributeObject${CLASS_SUFF} \
               EntityInfoAttribObject${CLASS_SUFF} \
               EntitySubsetInfo${CLASS_SUFF} \
               EntitySubsetInfoAttribObject${CLASS_SUFF} \
               EntitySynthesizer${CLASS_SUFF} \
               EntitySynthesizerException${CLASS_SUFF} \
               EntityTreeObject${CLASS_SUFF} \
               EntityTreeRoot${CLASS_SUFF} \
               EntityTreeRootException${CLASS_SUFF} \
               ExtendedSymbol${CLASS_SUFF} \
               FileAttribObject${CLASS_SUFF} \
               FileEntity${CLASS_SUFF} \
               FirstLevelStanza${CLASS_SUFF} \
               Generator${CLASS_SUFF} \
               GeneratorException${CLASS_SUFF} \
               GeneratorInterface${CLASS_SUFF} \
               InstallEntity${CLASS_SUFF} \
               InstallStatesInfoAttribObject${CLASS_SUFF} \
               JCLINGenerator${CLASS_SUFF} \
               LinkInfoAttribObject${CLASS_SUFF} \
               MkinstallGenerator${CLASS_SUFF} \
               MVSGenerator${CLASS_SUFF} \
               MvsInfoAttribObject${CLASS_SUFF} \
               Package${CLASS_SUFF} \
               PackageData${CLASS_SUFF} \
               PackageException${CLASS_SUFF} \
               PackageInfoAttribObject${CLASS_SUFF} \
               Parser${CLASS_SUFF} \
               ParserException${CLASS_SUFF} \
               ParserGeneratorEnumType${CLASS_SUFF} \
               ParserGeneratorInitiator${CLASS_SUFF} \
               ParserGeneratorInitiatorException${CLASS_SUFF} \
               PathInfoAttribObject${CLASS_SUFF} \
               PgSpecialType${CLASS_SUFF} \
               PkgDataAttribObject${CLASS_SUFF} \
               PkgmkGenerator${CLASS_SUFF} \
               ReqType${CLASS_SUFF} \
               RequisitesInfoAttribObject${CLASS_SUFF} \
               RPMGenerator${CLASS_SUFF} \
               Scanner${CLASS_SUFF} \
               ScannerException${CLASS_SUFF} \
               SecondLevelStanza${CLASS_SUFF} \
               ServiceInfoAttribObject${CLASS_SUFF} \
               SrcDataAttribObject${CLASS_SUFF} \
               StanzaCollection${CLASS_SUFF} \
               StanzaCollectionException${CLASS_SUFF} \
               SupportInfoAttribObject${CLASS_SUFF} \
               SwpackageGenerator${CLASS_SUFF} \
               Symbol${CLASS_SUFF} \
               VendorInfoAttribObject${CLASS_SUFF} \
               VplInfoAttribObject${CLASS_SUFF} 

.include <${RULES_MK}>















