# Header files to export
INCLUDES	= server.h mergeres.h

# Directory to where header files will be exported
EXPDIR		= /usr/include/

# Relative path from EXPDIR to the base of export
EXPTOP    = ../../

.include <${RULES_MK}>
