JAVA_CLASSES = PkgApiVrmf${CLASS_SUFF} \
               PkgApiVersion${CLASS_SUFF}

JAVADOCS = ${JAVA_PACKAGE_NAME}

JAVADOC_GENDIR = ${SANDBOXBASE}/export/javadocs/pkgapi

.include <$(RULES_MK)>
