JAVA_CLASSES = XMLElement${CLASS_SUFF} \
               Element${CLASS_SUFF} \
               FileStanza${CLASS_SUFF} \
               PackageData${CLASS_SUFF} \
               FileMetadata${CLASS_SUFF} \
               PartInfoElement${CLASS_SUFF} \
               PartInfoSubElement${CLASS_SUFF} \
               PropertyFileInterpreter${CLASS_SUFF} \
               TargetFileElement${CLASS_SUFF} \
               TargetDirElement${CLASS_SUFF} \
               Constants${CLASS_SUFF} \
               CMFGenerator${CLASS_SUFF} \
               FileHandlingUtilities${CLASS_SUFF} \
               MetaDataParser${CLASS_SUFF} \
               MetaDataContentHandler${CLASS_SUFF} \
               CMFFileStanza${CLASS_SUFF} \
               CMFSourceDataStanza${CLASS_SUFF} \
               CMFPackageDataStanza${CLASS_SUFF} \
               VariablesAndMessageHandler${CLASS_SUFF} 

.include <${RULES_MK}>
