JAVA_CLASSES = AixShellSystemCall${CLASS_SUFF} \
               EnumBase${CLASS_SUFF} \
               ErrorProcessMonitor${CLASS_SUFF} \
               ExceptionError${CLASS_SUFF} \
               FileHandleMonitor${CLASS_SUFF} \
               HPShellSystemCall${CLASS_SUFF} \
               Monitor${CLASS_SUFF} \
               MVSShellSystemCall${CLASS_SUFF} \
               NTShellSystemCall${CLASS_SUFF} \
               OS2ShellSystemCall${CLASS_SUFF} \
               OutputProcessMonitor${CLASS_SUFF} \
               PlatformShellSystemCall${CLASS_SUFF} \
               ProcessCreationError${CLASS_SUFF} \
               ProcessMonitor${CLASS_SUFF} \
               PropertyLookupException${CLASS_SUFF} \
               ShellSystemCall${CLASS_SUFF} \
               SolarisShellSystemCall${CLASS_SUFF} \
               SystemCall${CLASS_SUFF} \
               Utils${CLASS_SUFF} 

.include <$(RULES_MK)>
