JAVA_CLASSES = \
        TestPkgServer${CLASS_SUFF} \
        TestPkgClient${CLASS_SUFF} \
        TestPkgApi${CLASS_SUFF}

RMI_CLASSES = TestPkgApi${CLASS_SUFF}

JAVADOCS = ${JAVA_PACKAGE_NAME}

CLASSBASES = ${SANDBOXBASE}${CLASSGEN_SUBDIR}

JAVADOC_GENDIR = ${SANDBOXBASE}/export/javadocs/apitest

.include <${RULES_MK}>

