OBJECTS = string${OBJ_SUFF} strarray${OBJ_SUFF} pattern${OBJ_SUFF} \
          sboxcon${OBJ_SUFF} strcon${OBJ_SUFF} variable${OBJ_SUFF}

.ifdef WIN32
ODEDLLPORT=
.endif

# When library files are compiled, assume a DLL will be created
BUILD_SHARED_OBJECTS =

.include <${RULES_MK}>
