JAVA_CLASSES = B390APARDriver${CLASS_SUFF} \
               B390PTFDriver${CLASS_SUFF} \
               B390APARInfo${CLASS_SUFF} \
               B390APARBuildOptions${CLASS_SUFF} \
               B390DriverBuildOptions${CLASS_SUFF} \
               B390CommandException${CLASS_SUFF} \
               B390CommandHandler${CLASS_SUFF} \
               B390CommandInterface${CLASS_SUFF} \
               B390DriverBuildOptions${CLASS_SUFF} \
               B390Release${CLASS_SUFF} \
               RunMvsInitSvc${CLASS_SUFF} \
               RunMvsSvc${CLASS_SUFF} \
               PtfVplGenerator${CLASS_SUFF} \
               BPS_pkgapi${CLASS_SUFF}  

.include <${RULES_MK}>















