SUBDIRS = lib pkg bin
OBJECTS_SUBDIRS = lib pkg bin
JAVADOC_SUBDIRS = pkg
EXPINC_SUBDIRS = pkg/test

JAVA_CLASSES = MakeMake${CLASS_SUFF} \
               SandboxList${CLASS_SUFF} \
               SandboxFiles${CLASS_SUFF} \
               gui${CLASS_SUFF}

.include <${RULES_MK}>

