SUBDIRS = parserGenerator pkgCommon pkgMvs api test cmfgen
OBJECTS_SUBDIRS = parserGenerator pkgCommon pkgMvs api test cmfgen
JAVADOC_SUBDIRS = api test
EXPINC_SUBDIRS = test

.include <$(RULES_MK)>
